- name: variables
  hosts: local                                                        # local host
  connection: local
  vars:                                               #These are play-level variables, can be accessible to whole play
    Name: "kancharla ajay"
    Age: 25
    Gender: Male
    Color: Fair
  tasks:
  - name: Print the variables
    vars:                              # Task level variables, accessible only within the task. Task level variable can override play-lvel variables
      Name: "Bondada Vamsi"             
    ansible.builtin.debug:
     msg: "Name is {{ Name }}, Age is {{ Age }}, Gender is {{ Gender }}, Color is {{ Color }}"

