- name: Install the packages 
  hosts: Node1
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - gcc
    - mysql
    - zip