- name: Install the packages 
  hosts: Node1
  tasks:
  - name: Install packages
    ansible.builtin.packages:
      msg: "{{ item }}"
      state: present
    loop:
    - nginx
    - gcc
    - mysql
    - zip