- name: Install the packages 
  hosts: Node1
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'present' }
    - { name: 'gcc', state: 'absent' }
    - { name: 'zip', state: 'absent' }
    - { name: 'mysql', state: 'present' }