- name: Command or shell module when ansible module is not avaialble
  hosts: local
  connection: local
  tasks:
  - name: Execute ls command and redirect the output to the file
    #ansbile.builtin.command: ls -ltr > /tmp/output.txt      #This will not work because redirectors will not work for command module.
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
  
  - name: Execute ls command
    ansible.builtin.command: ls -ltr
    register: command_output_result                #Register is a key to store the command output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_output_result }}"